/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class AliasSetType extends java.util.AbstractList<SWIGTYPE_p_llvm__GlobalAlias> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AliasSetType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AliasSetType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_AliasSetType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AliasSetType(SWIGTYPE_p_llvm__GlobalAlias[] initialElements) {
    this();
    reserve(initialElements.length);

    for (SWIGTYPE_p_llvm__GlobalAlias element : initialElements) {
      add(element);
    }
  }

  public AliasSetType(Iterable<SWIGTYPE_p_llvm__GlobalAlias> initialElements) {
    this();
    for (SWIGTYPE_p_llvm__GlobalAlias element : initialElements) {
      add(element);
    }
  }

  public SWIGTYPE_p_llvm__GlobalAlias get(int index) {
    return doGet(index);
  }

  public SWIGTYPE_p_llvm__GlobalAlias set(int index, SWIGTYPE_p_llvm__GlobalAlias e) {
    return doSet(index, e);
  }

  public boolean add(SWIGTYPE_p_llvm__GlobalAlias e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, SWIGTYPE_p_llvm__GlobalAlias e) {
    modCount++;
    doAdd(index, e);
  }

  public SWIGTYPE_p_llvm__GlobalAlias remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public AliasSetType() {
    this(SUPAJNI.new_AliasSetType__SWIG_0(), true);
  }

  public AliasSetType(AliasSetType other) {
    this(SUPAJNI.new_AliasSetType__SWIG_1(AliasSetType.getCPtr(other), other), true);
  }

  public long capacity() {
    return SUPAJNI.AliasSetType_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SUPAJNI.AliasSetType_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SUPAJNI.AliasSetType_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SUPAJNI.AliasSetType_clear(swigCPtr, this);
  }

  public AliasSetType(int count, SWIGTYPE_p_llvm__GlobalAlias value) {
    this(SUPAJNI.new_AliasSetType__SWIG_2(count, SWIGTYPE_p_llvm__GlobalAlias.getCPtr(value)), true);
  }

  private int doSize() {
    return SUPAJNI.AliasSetType_doSize(swigCPtr, this);
  }

  private void doAdd(SWIGTYPE_p_llvm__GlobalAlias x) {
    SUPAJNI.AliasSetType_doAdd__SWIG_0(swigCPtr, this, SWIGTYPE_p_llvm__GlobalAlias.getCPtr(x));
  }

  private void doAdd(int index, SWIGTYPE_p_llvm__GlobalAlias x) {
    SUPAJNI.AliasSetType_doAdd__SWIG_1(swigCPtr, this, index, SWIGTYPE_p_llvm__GlobalAlias.getCPtr(x));
  }

  private SWIGTYPE_p_llvm__GlobalAlias doRemove(int index) {
    long cPtr = SUPAJNI.AliasSetType_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__GlobalAlias(cPtr, false);
  }

  private SWIGTYPE_p_llvm__GlobalAlias doGet(int index) {
    long cPtr = SUPAJNI.AliasSetType_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__GlobalAlias(cPtr, false);
  }

  private SWIGTYPE_p_llvm__GlobalAlias doSet(int index, SWIGTYPE_p_llvm__GlobalAlias val) {
    long cPtr = SUPAJNI.AliasSetType_doSet(swigCPtr, this, index, SWIGTYPE_p_llvm__GlobalAlias.getCPtr(val));
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__GlobalAlias(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SUPAJNI.AliasSetType_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
