/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class BasicBlockVector extends java.util.AbstractList<SWIGTYPE_p_llvm__BasicBlock> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BasicBlockVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BasicBlockVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_BasicBlockVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BasicBlockVector(SWIGTYPE_p_llvm__BasicBlock[] initialElements) {
    this();
    reserve(initialElements.length);

    for (SWIGTYPE_p_llvm__BasicBlock element : initialElements) {
      add(element);
    }
  }

  public BasicBlockVector(Iterable<SWIGTYPE_p_llvm__BasicBlock> initialElements) {
    this();
    for (SWIGTYPE_p_llvm__BasicBlock element : initialElements) {
      add(element);
    }
  }

  public SWIGTYPE_p_llvm__BasicBlock get(int index) {
    return doGet(index);
  }

  public SWIGTYPE_p_llvm__BasicBlock set(int index, SWIGTYPE_p_llvm__BasicBlock e) {
    return doSet(index, e);
  }

  public boolean add(SWIGTYPE_p_llvm__BasicBlock e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, SWIGTYPE_p_llvm__BasicBlock e) {
    modCount++;
    doAdd(index, e);
  }

  public SWIGTYPE_p_llvm__BasicBlock remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public BasicBlockVector() {
    this(SUPAJNI.new_BasicBlockVector__SWIG_0(), true);
  }

  public BasicBlockVector(BasicBlockVector other) {
    this(SUPAJNI.new_BasicBlockVector__SWIG_1(BasicBlockVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return SUPAJNI.BasicBlockVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SUPAJNI.BasicBlockVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SUPAJNI.BasicBlockVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SUPAJNI.BasicBlockVector_clear(swigCPtr, this);
  }

  public BasicBlockVector(int count, SWIGTYPE_p_llvm__BasicBlock value) {
    this(SUPAJNI.new_BasicBlockVector__SWIG_2(count, SWIGTYPE_p_llvm__BasicBlock.getCPtr(value)), true);
  }

  private int doSize() {
    return SUPAJNI.BasicBlockVector_doSize(swigCPtr, this);
  }

  private void doAdd(SWIGTYPE_p_llvm__BasicBlock x) {
    SUPAJNI.BasicBlockVector_doAdd__SWIG_0(swigCPtr, this, SWIGTYPE_p_llvm__BasicBlock.getCPtr(x));
  }

  private void doAdd(int index, SWIGTYPE_p_llvm__BasicBlock x) {
    SUPAJNI.BasicBlockVector_doAdd__SWIG_1(swigCPtr, this, index, SWIGTYPE_p_llvm__BasicBlock.getCPtr(x));
  }

  private SWIGTYPE_p_llvm__BasicBlock doRemove(int index) {
    long cPtr = SUPAJNI.BasicBlockVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__BasicBlock(cPtr, false);
  }

  private SWIGTYPE_p_llvm__BasicBlock doGet(int index) {
    long cPtr = SUPAJNI.BasicBlockVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__BasicBlock(cPtr, false);
  }

  private SWIGTYPE_p_llvm__BasicBlock doSet(int index, SWIGTYPE_p_llvm__BasicBlock val) {
    long cPtr = SUPAJNI.BasicBlockVector_doSet(swigCPtr, this, index, SWIGTYPE_p_llvm__BasicBlock.getCPtr(val));
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__BasicBlock(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SUPAJNI.BasicBlockVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
