/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class BVDataPTAImpl extends PointerAnalysis {
  private transient long swigCPtr;

  protected BVDataPTAImpl(long cPtr, boolean cMemoryOwn) {
    super(SUPAJNI.BVDataPTAImpl_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BVDataPTAImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_BVDataPTAImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void destroy() {
    SUPAJNI.BVDataPTAImpl_destroy(swigCPtr, this);
  }

  public SWIGTYPE_p_llvm__SparseBitVectorT_t getPts(long id) {
    return new SWIGTYPE_p_llvm__SparseBitVectorT_t(SUPAJNI.BVDataPTAImpl_getPts(swigCPtr, this, id), false);
  }

  public SWIGTYPE_p_llvm__SparseBitVectorT_t getRevPts(long nodeId) {
    return new SWIGTYPE_p_llvm__SparseBitVectorT_t(SUPAJNI.BVDataPTAImpl_getRevPts(swigCPtr, this, nodeId), false);
  }

  public void expandFIObjs(SWIGTYPE_p_llvm__SparseBitVectorT_t pts, SWIGTYPE_p_llvm__SparseBitVectorT_t expandedPts) {
    SUPAJNI.BVDataPTAImpl_expandFIObjs(swigCPtr, this, SWIGTYPE_p_llvm__SparseBitVectorT_t.getCPtr(pts), SWIGTYPE_p_llvm__SparseBitVectorT_t.getCPtr(expandedPts));
  }

  public void writeToFile(String filename) {
    SUPAJNI.BVDataPTAImpl_writeToFile(swigCPtr, this, filename);
  }

  public boolean readFromFile(String filename) {
    return SUPAJNI.BVDataPTAImpl_readFromFile(swigCPtr, this, filename);
  }

  public SWIGTYPE_p_llvm__AliasResult alias(SWIGTYPE_p_llvm__MemoryLocation LocA, SWIGTYPE_p_llvm__MemoryLocation LocB) {
    return new SWIGTYPE_p_llvm__AliasResult(SUPAJNI.BVDataPTAImpl_alias__SWIG_0(swigCPtr, this, SWIGTYPE_p_llvm__MemoryLocation.getCPtr(LocA), SWIGTYPE_p_llvm__MemoryLocation.getCPtr(LocB)), true);
  }

  public SWIGTYPE_p_llvm__AliasResult alias(SWIGTYPE_p_llvm__Value V1, SWIGTYPE_p_llvm__Value V2) {
    return new SWIGTYPE_p_llvm__AliasResult(SUPAJNI.BVDataPTAImpl_alias__SWIG_1(swigCPtr, this, SWIGTYPE_p_llvm__Value.getCPtr(V1), SWIGTYPE_p_llvm__Value.getCPtr(V2)), true);
  }

  public SWIGTYPE_p_llvm__AliasResult alias(long node1, long node2) {
    return new SWIGTYPE_p_llvm__AliasResult(SUPAJNI.BVDataPTAImpl_alias__SWIG_2(swigCPtr, this, node1, node2), true);
  }

  public SWIGTYPE_p_llvm__AliasResult alias(SWIGTYPE_p_llvm__SparseBitVectorT_t pts1, SWIGTYPE_p_llvm__SparseBitVectorT_t pts2) {
    return new SWIGTYPE_p_llvm__AliasResult(SUPAJNI.BVDataPTAImpl_alias__SWIG_3(swigCPtr, this, SWIGTYPE_p_llvm__SparseBitVectorT_t.getCPtr(pts1), SWIGTYPE_p_llvm__SparseBitVectorT_t.getCPtr(pts2)), true);
  }

  public void dumpCPts() {
    SUPAJNI.BVDataPTAImpl_dumpCPts(swigCPtr, this);
  }

  public void dumpTopLevelPtsTo() {
    SUPAJNI.BVDataPTAImpl_dumpTopLevelPtsTo(swigCPtr, this);
  }

  public void dumpAllPts() {
    SUPAJNI.BVDataPTAImpl_dumpAllPts(swigCPtr, this);
  }

}
