/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class CallEdgeMap extends java.util.AbstractMap<SWIGTYPE_p_llvm__CallSite, SWIGTYPE_p_FunctionSet> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CallEdgeMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CallEdgeMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_CallEdgeMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof SWIGTYPE_p_llvm__CallSite)) {
      return false;
    }

    return containsImpl((SWIGTYPE_p_llvm__CallSite)key);
  }

  public SWIGTYPE_p_FunctionSet get(java.lang.Object key) {
    if (!(key instanceof SWIGTYPE_p_llvm__CallSite)) {
      return null;
    }

    Iterator itr = find((SWIGTYPE_p_llvm__CallSite) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public SWIGTYPE_p_FunctionSet put(SWIGTYPE_p_llvm__CallSite key, SWIGTYPE_p_FunctionSet value) {
    Iterator itr = find((SWIGTYPE_p_llvm__CallSite) key);
    if (itr.isNot(end())) {
      SWIGTYPE_p_FunctionSet oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public SWIGTYPE_p_FunctionSet remove(java.lang.Object key) {
    if (!(key instanceof SWIGTYPE_p_llvm__CallSite)) {
      return null;
    }

    Iterator itr = find((SWIGTYPE_p_llvm__CallSite) key);
    if (itr.isNot(end())) {
      SWIGTYPE_p_FunctionSet oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<SWIGTYPE_p_llvm__CallSite, SWIGTYPE_p_FunctionSet>> entrySet() {
    java.util.Set<Entry<SWIGTYPE_p_llvm__CallSite, SWIGTYPE_p_FunctionSet>> setToReturn =
        new java.util.HashSet<Entry<SWIGTYPE_p_llvm__CallSite, SWIGTYPE_p_FunctionSet>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<SWIGTYPE_p_llvm__CallSite, SWIGTYPE_p_FunctionSet>() {
        private Iterator iterator;

        private Entry<SWIGTYPE_p_llvm__CallSite, SWIGTYPE_p_FunctionSet> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public SWIGTYPE_p_llvm__CallSite getKey() {
          return iterator.getKey();
        }

        public SWIGTYPE_p_FunctionSet getValue() {
          return iterator.getValue();
        }

        public SWIGTYPE_p_FunctionSet setValue(SWIGTYPE_p_FunctionSet newValue) {
          SWIGTYPE_p_FunctionSet oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public CallEdgeMap() {
    this(SUPAJNI.new_CallEdgeMap__SWIG_0(), true);
  }

  public CallEdgeMap(CallEdgeMap other) {
    this(SUPAJNI.new_CallEdgeMap__SWIG_1(CallEdgeMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SUPAJNI.delete_CallEdgeMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator getNextUnchecked() {
      return new SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator(SUPAJNI.CallEdgeMap_Iterator_getNextUnchecked(swigCPtr), true);
    }
  
    private boolean isNot(SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator other) {
      return SUPAJNI.CallEdgeMap_Iterator_isNot(swigCPtr, SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator.getCPtr(other));
    }
  
    private SWIGTYPE_p_llvm__CallSite getKey() {
      return new SWIGTYPE_p_llvm__CallSite(SUPAJNI.CallEdgeMap_Iterator_getKey(swigCPtr), true);
    }
  
    private SWIGTYPE_p_FunctionSet getValue() {
      return new SWIGTYPE_p_FunctionSet(SUPAJNI.CallEdgeMap_Iterator_getValue(swigCPtr), true);
    }
  
    private void setValue(SWIGTYPE_p_FunctionSet newValue) {
      SUPAJNI.CallEdgeMap_Iterator_setValue(swigCPtr, SWIGTYPE_p_FunctionSet.getCPtr(newValue));
    }
  
  }

  public boolean isEmpty() {
    return SUPAJNI.CallEdgeMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SUPAJNI.CallEdgeMap_clear(swigCPtr, this);
  }

  private SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator find(SWIGTYPE_p_llvm__CallSite key) {
    return new SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator(SUPAJNI.CallEdgeMap_find(swigCPtr, this, SWIGTYPE_p_llvm__CallSite.getCPtr(key)), true);
  }

  private SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator begin() {
    return new SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator(SUPAJNI.CallEdgeMap_begin(swigCPtr, this), true);
  }

  private SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator end() {
    return new SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator(SUPAJNI.CallEdgeMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return SUPAJNI.CallEdgeMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(SWIGTYPE_p_llvm__CallSite key) {
    return SUPAJNI.CallEdgeMap_containsImpl(swigCPtr, this, SWIGTYPE_p_llvm__CallSite.getCPtr(key));
  }

  private void putUnchecked(SWIGTYPE_p_llvm__CallSite key, SWIGTYPE_p_FunctionSet value) {
    SUPAJNI.CallEdgeMap_putUnchecked(swigCPtr, this, SWIGTYPE_p_llvm__CallSite.getCPtr(key), SWIGTYPE_p_FunctionSet.getCPtr(value));
  }

  private void removeUnchecked(SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator itr) {
    SUPAJNI.CallEdgeMap_removeUnchecked(swigCPtr, this, SWIGTYPE_p_std__mapT_llvm__CallSite_FunctionSet_std__lessT_llvm__CallSite_t_t__iterator.getCPtr(itr));
  }

}
