/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class CallSiteSet extends java.util.AbstractSet<SWIGTYPE_p_llvm__CallSite> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CallSiteSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CallSiteSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_CallSiteSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CallSiteSet(java.util.Collection<? extends SWIGTYPE_p_llvm__CallSite> collection) {
    this();
    addAll(collection);
  }

  public int size() {
    return sizeImpl();
  }

  public boolean add(SWIGTYPE_p_llvm__CallSite key) {
    return addImpl(key);
  }

  public boolean addAll(java.util.Collection<? extends SWIGTYPE_p_llvm__CallSite> collection) {
    boolean didAddElement = false;
    for (java.lang.Object object : collection) {
      didAddElement |= add((SWIGTYPE_p_llvm__CallSite)object);
    }

    return didAddElement;
  }

  public java.util.Iterator<SWIGTYPE_p_llvm__CallSite> iterator() {
    return new java.util.Iterator<SWIGTYPE_p_llvm__CallSite>() {
      private Iterator curr;
      private Iterator end;

      private java.util.Iterator<SWIGTYPE_p_llvm__CallSite> init() {
        curr = CallSiteSet.this.begin();
        end = CallSiteSet.this.end();
        return this;
      }

      public SWIGTYPE_p_llvm__CallSite next() {
        if (!hasNext()) {
          throw new java.util.NoSuchElementException();
        }

        // Save the current position, increment it,
        // then return the value at the position before the increment.
        final SWIGTYPE_p_llvm__CallSite currValue = curr.derefUnchecked();
        curr.incrementUnchecked();
        return currValue;
      }

      public boolean hasNext() {
        return curr.isNot(end);
      }
    }.init();
  }

  public boolean containsAll(java.util.Collection<?> collection) {
    for (java.lang.Object object : collection) {
      if (!contains(object)) {
        return false;
      }
    }

    return true;
  }

  public boolean contains(java.lang.Object object) {
    if (!(object instanceof SWIGTYPE_p_llvm__CallSite)) {
      return false;
    }

    return containsImpl((SWIGTYPE_p_llvm__CallSite)object);
  }

  public boolean removeAll(java.util.Collection<?> collection) {
    boolean didRemoveElement = false;
    for (java.lang.Object object : collection) {
      didRemoveElement |= remove(object);
    }

    return didRemoveElement;
  }

  public boolean remove(java.lang.Object object) {
    if (!(object instanceof SWIGTYPE_p_llvm__CallSite)) {
      return false;
    }

    return removeImpl((SWIGTYPE_p_llvm__CallSite)object);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SUPAJNI.delete_CallSiteSet_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private void incrementUnchecked() {
      SUPAJNI.CallSiteSet_Iterator_incrementUnchecked(swigCPtr);
    }
  
    private SWIGTYPE_p_llvm__CallSite derefUnchecked() {
      return new SWIGTYPE_p_llvm__CallSite(SUPAJNI.CallSiteSet_Iterator_derefUnchecked(swigCPtr), true);
    }
  
    private boolean isNot(SWIGTYPE_p_std__setT_llvm__CallSite_t__iterator other) {
      return SUPAJNI.CallSiteSet_Iterator_isNot(swigCPtr, SWIGTYPE_p_std__setT_llvm__CallSite_t__iterator.getCPtr(other));
    }
  
  }

  public CallSiteSet() {
    this(SUPAJNI.new_CallSiteSet__SWIG_0(), true);
  }

  public CallSiteSet(CallSiteSet other) {
    this(SUPAJNI.new_CallSiteSet__SWIG_1(CallSiteSet.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return SUPAJNI.CallSiteSet_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SUPAJNI.CallSiteSet_clear(swigCPtr, this);
  }

  private SWIGTYPE_p_std__setT_llvm__CallSite_t__iterator begin() {
    return new SWIGTYPE_p_std__setT_llvm__CallSite_t__iterator(SUPAJNI.CallSiteSet_begin(swigCPtr, this), true);
  }

  private SWIGTYPE_p_std__setT_llvm__CallSite_t__iterator end() {
    return new SWIGTYPE_p_std__setT_llvm__CallSite_t__iterator(SUPAJNI.CallSiteSet_end(swigCPtr, this), true);
  }

  public boolean addImpl(SWIGTYPE_p_llvm__CallSite key) {
    return SUPAJNI.CallSiteSet_addImpl(swigCPtr, this, SWIGTYPE_p_llvm__CallSite.getCPtr(key));
  }

  private boolean containsImpl(SWIGTYPE_p_llvm__CallSite key) {
    return SUPAJNI.CallSiteSet_containsImpl(swigCPtr, this, SWIGTYPE_p_llvm__CallSite.getCPtr(key));
  }

  private boolean removeImpl(SWIGTYPE_p_llvm__CallSite key) {
    return SUPAJNI.CallSiteSet_removeImpl(swigCPtr, this, SWIGTYPE_p_llvm__CallSite.getCPtr(key));
  }

  private int sizeImpl() {
    return SUPAJNI.CallSiteSet_sizeImpl(swigCPtr, this);
  }

  private boolean hasNextImpl(SWIGTYPE_p_std__setT_llvm__CallSite_t__iterator itr) {
    return SUPAJNI.CallSiteSet_hasNextImpl(swigCPtr, this, SWIGTYPE_p_std__setT_llvm__CallSite_t__iterator.getCPtr(itr));
  }

}
