/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class DDAClient {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DDAClient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DDAClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_DDAClient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DDAClient(SVFModule mod) {
    this(SUPAJNI.new_DDAClient(SVFModule.getCPtr(mod), mod), true);
  }

  public void initialise(SVFModule module) {
    SUPAJNI.DDAClient_initialise(swigCPtr, this, SVFModule.getCPtr(module), module);
  }

  public NodeSet collectCandidateQueries(SWIGTYPE_p_PAG p) {
    return new NodeSet(SUPAJNI.DDAClient_collectCandidateQueries(swigCPtr, this, SWIGTYPE_p_PAG.getCPtr(p)), false);
  }

  public NodeSet getCandidateQueries() {
    return new NodeSet(SUPAJNI.DDAClient_getCandidateQueries(swigCPtr, this), false);
  }

  public void handleStatement(SWIGTYPE_p_SVFGNode stmt, long var) {
    SUPAJNI.DDAClient_handleStatement(swigCPtr, this, SWIGTYPE_p_SVFGNode.getCPtr(stmt), var);
  }

  public void setPAG(SWIGTYPE_p_PAG g) {
    SUPAJNI.DDAClient_setPAG(swigCPtr, this, SWIGTYPE_p_PAG.getCPtr(g));
  }

  public void setCurrentQueryPtr(long ptr) {
    SUPAJNI.DDAClient_setCurrentQueryPtr(swigCPtr, this, ptr);
  }

  public void setQuery(long ptr) {
    SUPAJNI.DDAClient_setQuery(swigCPtr, this, ptr);
  }

  public SVFModule getModule() {
    return new SVFModule(SUPAJNI.DDAClient_getModule(swigCPtr, this), true);
  }

  public void answerQueries(PointerAnalysis pta) {
    SUPAJNI.DDAClient_answerQueries(swigCPtr, this, PointerAnalysis.getCPtr(pta), pta);
  }

  public void performStat(PointerAnalysis pta) {
    SUPAJNI.DDAClient_performStat(swigCPtr, this, PointerAnalysis.getCPtr(pta), pta);
  }

  public void collectWPANum(SVFModule mod) {
    SUPAJNI.DDAClient_collectWPANum(swigCPtr, this, SVFModule.getCPtr(mod), mod);
  }

}
