/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class DDAStat extends PTAStat {
  private transient long swigCPtr;

  protected DDAStat(long cPtr, boolean cMemoryOwn) {
    super(SUPAJNI.DDAStat_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DDAStat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_DDAStat(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DDAStat(SWIGTYPE_p_FlowDDA pta) {
    this(SUPAJNI.new_DDAStat__SWIG_0(SWIGTYPE_p_FlowDDA.getCPtr(pta)), true);
  }

  public DDAStat(SWIGTYPE_p_ContextDDA pta) {
    this(SUPAJNI.new_DDAStat__SWIG_1(SWIGTYPE_p_ContextDDA.getCPtr(pta)), true);
  }

  public void set_NumOfDPM(long value) {
    SUPAJNI.DDAStat__NumOfDPM_set(swigCPtr, this, value);
  }

  public long get_NumOfDPM() {
    return SUPAJNI.DDAStat__NumOfDPM_get(swigCPtr, this);
  }

  public void set_NumOfStrongUpdates(long value) {
    SUPAJNI.DDAStat__NumOfStrongUpdates_set(swigCPtr, this, value);
  }

  public long get_NumOfStrongUpdates() {
    return SUPAJNI.DDAStat__NumOfStrongUpdates_get(swigCPtr, this);
  }

  public void set_NumOfMustAliases(long value) {
    SUPAJNI.DDAStat__NumOfMustAliases_set(swigCPtr, this, value);
  }

  public long get_NumOfMustAliases() {
    return SUPAJNI.DDAStat__NumOfMustAliases_get(swigCPtr, this);
  }

  public void set_NumOfInfeasiblePath(long value) {
    SUPAJNI.DDAStat__NumOfInfeasiblePath_set(swigCPtr, this, value);
  }

  public long get_NumOfInfeasiblePath() {
    return SUPAJNI.DDAStat__NumOfInfeasiblePath_get(swigCPtr, this);
  }

  public void set_NumOfStep(java.math.BigInteger value) {
    SUPAJNI.DDAStat__NumOfStep_set(swigCPtr, this, value);
  }

  public java.math.BigInteger get_NumOfStep() {
    return SUPAJNI.DDAStat__NumOfStep_get(swigCPtr, this);
  }

  public void set_NumOfStepInCycle(java.math.BigInteger value) {
    SUPAJNI.DDAStat__NumOfStepInCycle_set(swigCPtr, this, value);
  }

  public java.math.BigInteger get_NumOfStepInCycle() {
    return SUPAJNI.DDAStat__NumOfStepInCycle_get(swigCPtr, this);
  }

  public void set_AnaTimePerQuery(double value) {
    SUPAJNI.DDAStat__AnaTimePerQuery_set(swigCPtr, this, value);
  }

  public double get_AnaTimePerQuery() {
    return SUPAJNI.DDAStat__AnaTimePerQuery_get(swigCPtr, this);
  }

  public void set_AnaTimeCyclePerQuery(double value) {
    SUPAJNI.DDAStat__AnaTimeCyclePerQuery_set(swigCPtr, this, value);
  }

  public double get_AnaTimeCyclePerQuery() {
    return SUPAJNI.DDAStat__AnaTimeCyclePerQuery_get(swigCPtr, this);
  }

  public void set_TotalTimeOfQueries(double value) {
    SUPAJNI.DDAStat__TotalTimeOfQueries_set(swigCPtr, this, value);
  }

  public double get_TotalTimeOfQueries() {
    return SUPAJNI.DDAStat__TotalTimeOfQueries_get(swigCPtr, this);
  }

  public void set_TotalTimeOfBKCondition(double value) {
    SUPAJNI.DDAStat__TotalTimeOfBKCondition_set(swigCPtr, this, value);
  }

  public double get_TotalTimeOfBKCondition() {
    return SUPAJNI.DDAStat__TotalTimeOfBKCondition_get(swigCPtr, this);
  }

  public void set_StrongUpdateStores(SWIGTYPE_p_llvm__SparseBitVectorT_t value) {
    SUPAJNI.DDAStat__StrongUpdateStores_set(swigCPtr, this, SWIGTYPE_p_llvm__SparseBitVectorT_t.getCPtr(value));
  }

  public SWIGTYPE_p_llvm__SparseBitVectorT_t get_StrongUpdateStores() {
    return new SWIGTYPE_p_llvm__SparseBitVectorT_t(SUPAJNI.DDAStat__StrongUpdateStores_get(swigCPtr, this), true);
  }

  public void performStatPerQuery(long ptr) {
    SUPAJNI.DDAStat_performStatPerQuery(swigCPtr, this, ptr);
  }

  public void performStat() {
    SUPAJNI.DDAStat_performStat(swigCPtr, this);
  }

  public void printStat() {
    SUPAJNI.DDAStat_printStat(swigCPtr, this);
  }

  public void printStatPerQuery(long ptr, SWIGTYPE_p_llvm__SparseBitVectorT_t pts) {
    SUPAJNI.DDAStat_printStatPerQuery(swigCPtr, this, ptr, SWIGTYPE_p_llvm__SparseBitVectorT_t.getCPtr(pts));
  }

  public void getNumOfOOBQuery() {
    SUPAJNI.DDAStat_getNumOfOOBQuery(swigCPtr, this);
  }

  public void setMemUsageBefore(long vmrss, long vmsize) {
    SUPAJNI.DDAStat_setMemUsageBefore(swigCPtr, this, vmrss, vmsize);
  }

  public void setMemUsageAfter(long vmrss, long vmsize) {
    SUPAJNI.DDAStat_setMemUsageAfter(swigCPtr, this, vmrss, vmsize);
  }

  public SWIGTYPE_p_SVFG getSVFG() {
    long cPtr = SUPAJNI.DDAStat_getSVFG(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SVFG(cPtr, false);
  }

  public PointerAnalysis getPTA() {
    long cPtr = SUPAJNI.DDAStat_getPTA(swigCPtr, this);
    return (cPtr == 0) ? null : new PointerAnalysis(cPtr, false);
  }

  public SWIGTYPE_p_llvm__SparseBitVectorT_t getStrongUpdateStores() {
    return new SWIGTYPE_p_llvm__SparseBitVectorT_t(SUPAJNI.DDAStat_getStrongUpdateStores(swigCPtr, this), false);
  }

}
