/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class DPItemToCPtSetMap extends java.util.AbstractMap<SWIGTYPE_p_DPItem, SWIGTYPE_p_CPtSet> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DPItemToCPtSetMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DPItemToCPtSetMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_DPItemToCPtSetMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof SWIGTYPE_p_DPItem)) {
      return false;
    }

    return containsImpl((SWIGTYPE_p_DPItem)key);
  }

  public SWIGTYPE_p_CPtSet get(java.lang.Object key) {
    if (!(key instanceof SWIGTYPE_p_DPItem)) {
      return null;
    }

    Iterator itr = find((SWIGTYPE_p_DPItem) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public SWIGTYPE_p_CPtSet put(SWIGTYPE_p_DPItem key, SWIGTYPE_p_CPtSet value) {
    Iterator itr = find((SWIGTYPE_p_DPItem) key);
    if (itr.isNot(end())) {
      SWIGTYPE_p_CPtSet oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public SWIGTYPE_p_CPtSet remove(java.lang.Object key) {
    if (!(key instanceof SWIGTYPE_p_DPItem)) {
      return null;
    }

    Iterator itr = find((SWIGTYPE_p_DPItem) key);
    if (itr.isNot(end())) {
      SWIGTYPE_p_CPtSet oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<SWIGTYPE_p_DPItem, SWIGTYPE_p_CPtSet>> entrySet() {
    java.util.Set<Entry<SWIGTYPE_p_DPItem, SWIGTYPE_p_CPtSet>> setToReturn =
        new java.util.HashSet<Entry<SWIGTYPE_p_DPItem, SWIGTYPE_p_CPtSet>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<SWIGTYPE_p_DPItem, SWIGTYPE_p_CPtSet>() {
        private Iterator iterator;

        private Entry<SWIGTYPE_p_DPItem, SWIGTYPE_p_CPtSet> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public SWIGTYPE_p_DPItem getKey() {
          return iterator.getKey();
        }

        public SWIGTYPE_p_CPtSet getValue() {
          return iterator.getValue();
        }

        public SWIGTYPE_p_CPtSet setValue(SWIGTYPE_p_CPtSet newValue) {
          SWIGTYPE_p_CPtSet oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public DPItemToCPtSetMap() {
    this(SUPAJNI.new_DPItemToCPtSetMap__SWIG_0(), true);
  }

  public DPItemToCPtSetMap(DPItemToCPtSetMap other) {
    this(SUPAJNI.new_DPItemToCPtSetMap__SWIG_1(DPItemToCPtSetMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SUPAJNI.delete_DPItemToCPtSetMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private DPItemToCPtSetMap.Iterator getNextUnchecked() {
      return new DPItemToCPtSetMap.Iterator(SUPAJNI.DPItemToCPtSetMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(DPItemToCPtSetMap.Iterator other) {
      return SUPAJNI.DPItemToCPtSetMap_Iterator_isNot(swigCPtr, this, DPItemToCPtSetMap.Iterator.getCPtr(other), other);
    }
  
    private SWIGTYPE_p_DPItem getKey() {
      return new SWIGTYPE_p_DPItem(SUPAJNI.DPItemToCPtSetMap_Iterator_getKey(swigCPtr, this), true);
    }
  
    private SWIGTYPE_p_CPtSet getValue() {
      return new SWIGTYPE_p_CPtSet(SUPAJNI.DPItemToCPtSetMap_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(SWIGTYPE_p_CPtSet newValue) {
      SUPAJNI.DPItemToCPtSetMap_Iterator_setValue(swigCPtr, this, SWIGTYPE_p_CPtSet.getCPtr(newValue));
    }
  
  }

  public boolean isEmpty() {
    return SUPAJNI.DPItemToCPtSetMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SUPAJNI.DPItemToCPtSetMap_clear(swigCPtr, this);
  }

  private DPItemToCPtSetMap.Iterator find(SWIGTYPE_p_DPItem key) {
    return new DPItemToCPtSetMap.Iterator(SUPAJNI.DPItemToCPtSetMap_find(swigCPtr, this, SWIGTYPE_p_DPItem.getCPtr(key)), true);
  }

  private DPItemToCPtSetMap.Iterator begin() {
    return new DPItemToCPtSetMap.Iterator(SUPAJNI.DPItemToCPtSetMap_begin(swigCPtr, this), true);
  }

  private DPItemToCPtSetMap.Iterator end() {
    return new DPItemToCPtSetMap.Iterator(SUPAJNI.DPItemToCPtSetMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return SUPAJNI.DPItemToCPtSetMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(SWIGTYPE_p_DPItem key) {
    return SUPAJNI.DPItemToCPtSetMap_containsImpl(swigCPtr, this, SWIGTYPE_p_DPItem.getCPtr(key));
  }

  private void putUnchecked(SWIGTYPE_p_DPItem key, SWIGTYPE_p_CPtSet value) {
    SUPAJNI.DPItemToCPtSetMap_putUnchecked(swigCPtr, this, SWIGTYPE_p_DPItem.getCPtr(key), SWIGTYPE_p_CPtSet.getCPtr(value));
  }

  private void removeUnchecked(DPItemToCPtSetMap.Iterator itr) {
    SUPAJNI.DPItemToCPtSetMap_removeUnchecked(swigCPtr, this, DPItemToCPtSetMap.Iterator.getCPtr(itr), itr);
  }

}
