/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class FunctionSetType extends java.util.AbstractList<SWIGTYPE_p_llvm__Function> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FunctionSetType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FunctionSetType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_FunctionSetType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FunctionSetType(SWIGTYPE_p_llvm__Function[] initialElements) {
    this();
    reserve(initialElements.length);

    for (SWIGTYPE_p_llvm__Function element : initialElements) {
      add(element);
    }
  }

  public FunctionSetType(Iterable<SWIGTYPE_p_llvm__Function> initialElements) {
    this();
    for (SWIGTYPE_p_llvm__Function element : initialElements) {
      add(element);
    }
  }

  public SWIGTYPE_p_llvm__Function get(int index) {
    return doGet(index);
  }

  public SWIGTYPE_p_llvm__Function set(int index, SWIGTYPE_p_llvm__Function e) {
    return doSet(index, e);
  }

  public boolean add(SWIGTYPE_p_llvm__Function e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, SWIGTYPE_p_llvm__Function e) {
    modCount++;
    doAdd(index, e);
  }

  public SWIGTYPE_p_llvm__Function remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public FunctionSetType() {
    this(SUPAJNI.new_FunctionSetType__SWIG_0(), true);
  }

  public FunctionSetType(FunctionSetType other) {
    this(SUPAJNI.new_FunctionSetType__SWIG_1(FunctionSetType.getCPtr(other), other), true);
  }

  public long capacity() {
    return SUPAJNI.FunctionSetType_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SUPAJNI.FunctionSetType_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SUPAJNI.FunctionSetType_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SUPAJNI.FunctionSetType_clear(swigCPtr, this);
  }

  public FunctionSetType(int count, SWIGTYPE_p_llvm__Function value) {
    this(SUPAJNI.new_FunctionSetType__SWIG_2(count, SWIGTYPE_p_llvm__Function.getCPtr(value)), true);
  }

  private int doSize() {
    return SUPAJNI.FunctionSetType_doSize(swigCPtr, this);
  }

  private void doAdd(SWIGTYPE_p_llvm__Function x) {
    SUPAJNI.FunctionSetType_doAdd__SWIG_0(swigCPtr, this, SWIGTYPE_p_llvm__Function.getCPtr(x));
  }

  private void doAdd(int index, SWIGTYPE_p_llvm__Function x) {
    SUPAJNI.FunctionSetType_doAdd__SWIG_1(swigCPtr, this, index, SWIGTYPE_p_llvm__Function.getCPtr(x));
  }

  private SWIGTYPE_p_llvm__Function doRemove(int index) {
    long cPtr = SUPAJNI.FunctionSetType_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__Function(cPtr, false);
  }

  private SWIGTYPE_p_llvm__Function doGet(int index) {
    long cPtr = SUPAJNI.FunctionSetType_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__Function(cPtr, false);
  }

  private SWIGTYPE_p_llvm__Function doSet(int index, SWIGTYPE_p_llvm__Function val) {
    long cPtr = SUPAJNI.FunctionSetType_doSet(swigCPtr, this, index, SWIGTYPE_p_llvm__Function.getCPtr(val));
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__Function(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SUPAJNI.FunctionSetType_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
