/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class NodeSet extends java.util.AbstractSet<Long> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NodeSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodeSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_NodeSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NodeSet(java.util.Collection<? extends Long> collection) {
    this();
    addAll(collection);
  }

  public int size() {
    return sizeImpl();
  }

  public boolean add(Long key) {
    return addImpl(key);
  }

  public boolean addAll(java.util.Collection<? extends Long> collection) {
    boolean didAddElement = false;
    for (java.lang.Object object : collection) {
      didAddElement |= add((Long)object);
    }

    return didAddElement;
  }

  public java.util.Iterator<Long> iterator() {
    return new java.util.Iterator<Long>() {
      private Iterator curr;
      private Iterator end;

      private java.util.Iterator<Long> init() {
        curr = NodeSet.this.begin();
        end = NodeSet.this.end();
        return this;
      }

      public Long next() {
        if (!hasNext()) {
          throw new java.util.NoSuchElementException();
        }

        // Save the current position, increment it,
        // then return the value at the position before the increment.
        final Long currValue = curr.derefUnchecked();
        curr.incrementUnchecked();
        return currValue;
      }

      public boolean hasNext() {
        return curr.isNot(end);
      }
    }.init();
  }

  public boolean containsAll(java.util.Collection<?> collection) {
    for (java.lang.Object object : collection) {
      if (!contains(object)) {
        return false;
      }
    }

    return true;
  }

  public boolean contains(java.lang.Object object) {
    if (!(object instanceof Long)) {
      return false;
    }

    return containsImpl((Long)object);
  }

  public boolean removeAll(java.util.Collection<?> collection) {
    boolean didRemoveElement = false;
    for (java.lang.Object object : collection) {
      didRemoveElement |= remove(object);
    }

    return didRemoveElement;
  }

  public boolean remove(java.lang.Object object) {
    if (!(object instanceof Long)) {
      return false;
    }

    return removeImpl((Long)object);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SUPAJNI.delete_NodeSet_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private void incrementUnchecked() {
      SUPAJNI.NodeSet_Iterator_incrementUnchecked(swigCPtr);
    }
  
    private long derefUnchecked() {
      return SUPAJNI.NodeSet_Iterator_derefUnchecked(swigCPtr);
    }
  
    private boolean isNot(SWIGTYPE_p_std__setT_unsigned_int_t__iterator other) {
      return SUPAJNI.NodeSet_Iterator_isNot(swigCPtr, SWIGTYPE_p_std__setT_unsigned_int_t__iterator.getCPtr(other));
    }
  
  }

  public NodeSet() {
    this(SUPAJNI.new_NodeSet__SWIG_0(), true);
  }

  public NodeSet(NodeSet other) {
    this(SUPAJNI.new_NodeSet__SWIG_1(NodeSet.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return SUPAJNI.NodeSet_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SUPAJNI.NodeSet_clear(swigCPtr, this);
  }

  private SWIGTYPE_p_std__setT_unsigned_int_t__iterator begin() {
    return new SWIGTYPE_p_std__setT_unsigned_int_t__iterator(SUPAJNI.NodeSet_begin(swigCPtr, this), true);
  }

  private SWIGTYPE_p_std__setT_unsigned_int_t__iterator end() {
    return new SWIGTYPE_p_std__setT_unsigned_int_t__iterator(SUPAJNI.NodeSet_end(swigCPtr, this), true);
  }

  public boolean addImpl(long key) {
    return SUPAJNI.NodeSet_addImpl(swigCPtr, this, key);
  }

  private boolean containsImpl(long key) {
    return SUPAJNI.NodeSet_containsImpl(swigCPtr, this, key);
  }

  private boolean removeImpl(long key) {
    return SUPAJNI.NodeSet_removeImpl(swigCPtr, this, key);
  }

  private int sizeImpl() {
    return SUPAJNI.NodeSet_sizeImpl(swigCPtr, this);
  }

  private boolean hasNextImpl(SWIGTYPE_p_std__setT_unsigned_int_t__iterator itr) {
    return SUPAJNI.NodeSet_hasNextImpl(swigCPtr, this, SWIGTYPE_p_std__setT_unsigned_int_t__iterator.getCPtr(itr));
  }

}
