/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class NodePair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NodePair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodePair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_NodePair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NodePair() {
    this(SUPAJNI.new_NodePair__SWIG_0(), true);
  }

  public NodePair(long first, long second) {
    this(SUPAJNI.new_NodePair__SWIG_1(first, second), true);
  }

  public NodePair(NodePair other) {
    this(SUPAJNI.new_NodePair__SWIG_2(NodePair.getCPtr(other), other), true);
  }

  public void setFirst(long value) {
    SUPAJNI.NodePair_first_set(swigCPtr, this, value);
  }

  public long getFirst() {
    return SUPAJNI.NodePair_first_get(swigCPtr, this);
  }

  public void setSecond(long value) {
    SUPAJNI.NodePair_second_set(swigCPtr, this, value);
  }

  public long getSecond() {
    return SUPAJNI.NodePair_second_get(swigCPtr, this);
  }

}
