/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class NUMStatMap extends java.util.AbstractMap<String, Long> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NUMStatMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NUMStatMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_NUMStatMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public Long get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public Long put(String key, Long value) {
    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      Long oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public Long remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      Long oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, Long>> entrySet() {
    java.util.Set<Entry<String, Long>> setToReturn =
        new java.util.HashSet<Entry<String, Long>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, Long>() {
        private Iterator iterator;

        private Entry<String, Long> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public Long getValue() {
          return iterator.getValue();
        }

        public Long setValue(Long newValue) {
          Long oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public NUMStatMap() {
    this(SUPAJNI.new_NUMStatMap__SWIG_0(), true);
  }

  public NUMStatMap(NUMStatMap other) {
    this(SUPAJNI.new_NUMStatMap__SWIG_1(NUMStatMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SUPAJNI.delete_NUMStatMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator getNextUnchecked() {
      return new SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator(SUPAJNI.NUMStatMap_Iterator_getNextUnchecked(swigCPtr), true);
    }
  
    private boolean isNot(SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator other) {
      return SUPAJNI.NUMStatMap_Iterator_isNot(swigCPtr, SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator.getCPtr(other));
    }
  
    private String getKey() {
      return SUPAJNI.NUMStatMap_Iterator_getKey(swigCPtr);
    }
  
    private long getValue() {
      return SUPAJNI.NUMStatMap_Iterator_getValue(swigCPtr);
    }
  
    private void setValue(long newValue) {
      SUPAJNI.NUMStatMap_Iterator_setValue(swigCPtr, newValue);
    }
  
  }

  public boolean isEmpty() {
    return SUPAJNI.NUMStatMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SUPAJNI.NUMStatMap_clear(swigCPtr, this);
  }

  private SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator find(String key) {
    return new SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator(SUPAJNI.NUMStatMap_find(swigCPtr, this, key), true);
  }

  private SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator begin() {
    return new SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator(SUPAJNI.NUMStatMap_begin(swigCPtr, this), true);
  }

  private SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator end() {
    return new SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator(SUPAJNI.NUMStatMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return SUPAJNI.NUMStatMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return SUPAJNI.NUMStatMap_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, long value) {
    SUPAJNI.NUMStatMap_putUnchecked(swigCPtr, this, key, value);
  }

  private void removeUnchecked(SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator itr) {
    SUPAJNI.NUMStatMap_removeUnchecked(swigCPtr, this, SWIGTYPE_p_std__mapT_char_const_p_unsigned_int_std__lessT_char_const_p_t_t__iterator.getCPtr(itr));
  }

}
