/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class PTAStat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PTAStat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PTAStat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_PTAStat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void setTotalAnalysisTime(String value) {
    SUPAJNI.PTAStat_TotalAnalysisTime_set(value);
  }

  public static String getTotalAnalysisTime() {
    return SUPAJNI.PTAStat_TotalAnalysisTime_get();
  }

  public static void setSCCDetectionTime(String value) {
    SUPAJNI.PTAStat_SCCDetectionTime_set(value);
  }

  public static String getSCCDetectionTime() {
    return SUPAJNI.PTAStat_SCCDetectionTime_get();
  }

  public static void setSCCMergeTime(String value) {
    SUPAJNI.PTAStat_SCCMergeTime_set(value);
  }

  public static String getSCCMergeTime() {
    return SUPAJNI.PTAStat_SCCMergeTime_get();
  }

  public static void setProcessLoadStoreTime(String value) {
    SUPAJNI.PTAStat_ProcessLoadStoreTime_set(value);
  }

  public static String getProcessLoadStoreTime() {
    return SUPAJNI.PTAStat_ProcessLoadStoreTime_get();
  }

  public static void setProcessCopyGepTime(String value) {
    SUPAJNI.PTAStat_ProcessCopyGepTime_set(value);
  }

  public static String getProcessCopyGepTime() {
    return SUPAJNI.PTAStat_ProcessCopyGepTime_get();
  }

  public static void setUpdateCallGraphTime(String value) {
    SUPAJNI.PTAStat_UpdateCallGraphTime_set(value);
  }

  public static String getUpdateCallGraphTime() {
    return SUPAJNI.PTAStat_UpdateCallGraphTime_get();
  }

  public static void setTotalNumOfPointers(String value) {
    SUPAJNI.PTAStat_TotalNumOfPointers_set(value);
  }

  public static String getTotalNumOfPointers() {
    return SUPAJNI.PTAStat_TotalNumOfPointers_get();
  }

  public static void setTotalNumOfObjects(String value) {
    SUPAJNI.PTAStat_TotalNumOfObjects_set(value);
  }

  public static String getTotalNumOfObjects() {
    return SUPAJNI.PTAStat_TotalNumOfObjects_get();
  }

  public static void setTotalNumOfFieldObjects(String value) {
    SUPAJNI.PTAStat_TotalNumOfFieldObjects_set(value);
  }

  public static String getTotalNumOfFieldObjects() {
    return SUPAJNI.PTAStat_TotalNumOfFieldObjects_get();
  }

  public static void setMaxStructSize(String value) {
    SUPAJNI.PTAStat_MaxStructSize_set(value);
  }

  public static String getMaxStructSize() {
    return SUPAJNI.PTAStat_MaxStructSize_get();
  }

  public static void setTotalNumOfEdges(String value) {
    SUPAJNI.PTAStat_TotalNumOfEdges_set(value);
  }

  public static String getTotalNumOfEdges() {
    return SUPAJNI.PTAStat_TotalNumOfEdges_get();
  }

  public static void setNumOfAddrs(String value) {
    SUPAJNI.PTAStat_NumOfAddrs_set(value);
  }

  public static String getNumOfAddrs() {
    return SUPAJNI.PTAStat_NumOfAddrs_get();
  }

  public static void setNumOfLoads(String value) {
    SUPAJNI.PTAStat_NumOfLoads_set(value);
  }

  public static String getNumOfLoads() {
    return SUPAJNI.PTAStat_NumOfLoads_get();
  }

  public static void setNumOfStores(String value) {
    SUPAJNI.PTAStat_NumOfStores_set(value);
  }

  public static String getNumOfStores() {
    return SUPAJNI.PTAStat_NumOfStores_get();
  }

  public static void setNumOfCopys(String value) {
    SUPAJNI.PTAStat_NumOfCopys_set(value);
  }

  public static String getNumOfCopys() {
    return SUPAJNI.PTAStat_NumOfCopys_get();
  }

  public static void setNumOfGeps(String value) {
    SUPAJNI.PTAStat_NumOfGeps_set(value);
  }

  public static String getNumOfGeps() {
    return SUPAJNI.PTAStat_NumOfGeps_get();
  }

  public static void setNumOfCalls(String value) {
    SUPAJNI.PTAStat_NumOfCalls_set(value);
  }

  public static String getNumOfCalls() {
    return SUPAJNI.PTAStat_NumOfCalls_get();
  }

  public static void setNumOfReturns(String value) {
    SUPAJNI.PTAStat_NumOfReturns_set(value);
  }

  public static String getNumOfReturns() {
    return SUPAJNI.PTAStat_NumOfReturns_get();
  }

  public static void setNumOfProcessedAddrs(String value) {
    SUPAJNI.PTAStat_NumOfProcessedAddrs_set(value);
  }

  public static String getNumOfProcessedAddrs() {
    return SUPAJNI.PTAStat_NumOfProcessedAddrs_get();
  }

  public static void setNumOfProcessedLoads(String value) {
    SUPAJNI.PTAStat_NumOfProcessedLoads_set(value);
  }

  public static String getNumOfProcessedLoads() {
    return SUPAJNI.PTAStat_NumOfProcessedLoads_get();
  }

  public static void setNumOfProcessedStores(String value) {
    SUPAJNI.PTAStat_NumOfProcessedStores_set(value);
  }

  public static String getNumOfProcessedStores() {
    return SUPAJNI.PTAStat_NumOfProcessedStores_get();
  }

  public static void setNumOfProcessedCopys(String value) {
    SUPAJNI.PTAStat_NumOfProcessedCopys_set(value);
  }

  public static String getNumOfProcessedCopys() {
    return SUPAJNI.PTAStat_NumOfProcessedCopys_get();
  }

  public static void setNumOfProcessedGeps(String value) {
    SUPAJNI.PTAStat_NumOfProcessedGeps_set(value);
  }

  public static String getNumOfProcessedGeps() {
    return SUPAJNI.PTAStat_NumOfProcessedGeps_get();
  }

  public static void setNumOfSfr(String value) {
    SUPAJNI.PTAStat_NumOfSfr_set(value);
  }

  public static String getNumOfSfr() {
    return SUPAJNI.PTAStat_NumOfSfr_get();
  }

  public static void setNumOfFieldExpand(String value) {
    SUPAJNI.PTAStat_NumOfFieldExpand_set(value);
  }

  public static String getNumOfFieldExpand() {
    return SUPAJNI.PTAStat_NumOfFieldExpand_get();
  }

  public static void setNumOfFunctionObjs(String value) {
    SUPAJNI.PTAStat_NumOfFunctionObjs_set(value);
  }

  public static String getNumOfFunctionObjs() {
    return SUPAJNI.PTAStat_NumOfFunctionObjs_get();
  }

  public static void setNumOfGlobalObjs(String value) {
    SUPAJNI.PTAStat_NumOfGlobalObjs_set(value);
  }

  public static String getNumOfGlobalObjs() {
    return SUPAJNI.PTAStat_NumOfGlobalObjs_get();
  }

  public static void setNumOfHeapObjs(String value) {
    SUPAJNI.PTAStat_NumOfHeapObjs_set(value);
  }

  public static String getNumOfHeapObjs() {
    return SUPAJNI.PTAStat_NumOfHeapObjs_get();
  }

  public static void setNumOfStackObjs(String value) {
    SUPAJNI.PTAStat_NumOfStackObjs_set(value);
  }

  public static String getNumOfStackObjs() {
    return SUPAJNI.PTAStat_NumOfStackObjs_get();
  }

  public static void setNumOfObjsHasVarStruct(String value) {
    SUPAJNI.PTAStat_NumOfObjsHasVarStruct_set(value);
  }

  public static String getNumOfObjsHasVarStruct() {
    return SUPAJNI.PTAStat_NumOfObjsHasVarStruct_get();
  }

  public static void setNumOfObjsHasVarArray(String value) {
    SUPAJNI.PTAStat_NumOfObjsHasVarArray_set(value);
  }

  public static String getNumOfObjsHasVarArray() {
    return SUPAJNI.PTAStat_NumOfObjsHasVarArray_get();
  }

  public static void setNumOfObjsHasConstStruct(String value) {
    SUPAJNI.PTAStat_NumOfObjsHasConstStruct_set(value);
  }

  public static String getNumOfObjsHasConstStruct() {
    return SUPAJNI.PTAStat_NumOfObjsHasConstStruct_get();
  }

  public static void setNumOfObjsHasConstArray(String value) {
    SUPAJNI.PTAStat_NumOfObjsHasConstArray_set(value);
  }

  public static String getNumOfObjsHasConstArray() {
    return SUPAJNI.PTAStat_NumOfObjsHasConstArray_get();
  }

  public static void setNumOfNonPtrObjs(String value) {
    SUPAJNI.PTAStat_NumOfNonPtrObjs_set(value);
  }

  public static String getNumOfNonPtrObjs() {
    return SUPAJNI.PTAStat_NumOfNonPtrObjs_get();
  }

  public static void setNumOfConstantObjs(String value) {
    SUPAJNI.PTAStat_NumOfConstantObjs_set(value);
  }

  public static String getNumOfConstantObjs() {
    return SUPAJNI.PTAStat_NumOfConstantObjs_get();
  }

  public static void setNumberOfFieldInsensitiveObj(String value) {
    SUPAJNI.PTAStat_NumberOfFieldInsensitiveObj_set(value);
  }

  public static String getNumberOfFieldInsensitiveObj() {
    return SUPAJNI.PTAStat_NumberOfFieldInsensitiveObj_get();
  }

  public static void setNumberOfFieldSensitiveObj(String value) {
    SUPAJNI.PTAStat_NumberOfFieldSensitiveObj_set(value);
  }

  public static String getNumberOfFieldSensitiveObj() {
    return SUPAJNI.PTAStat_NumberOfFieldSensitiveObj_get();
  }

  public static void setNumOfPointers(String value) {
    SUPAJNI.PTAStat_NumOfPointers_set(value);
  }

  public static String getNumOfPointers() {
    return SUPAJNI.PTAStat_NumOfPointers_get();
  }

  public static void setNumOfGepFieldPointers(String value) {
    SUPAJNI.PTAStat_NumOfGepFieldPointers_set(value);
  }

  public static String getNumOfGepFieldPointers() {
    return SUPAJNI.PTAStat_NumOfGepFieldPointers_get();
  }

  public static void setNumOfMemObjects(String value) {
    SUPAJNI.PTAStat_NumOfMemObjects_set(value);
  }

  public static String getNumOfMemObjects() {
    return SUPAJNI.PTAStat_NumOfMemObjects_get();
  }

  public static void setNumOfGepFieldObjects(String value) {
    SUPAJNI.PTAStat_NumOfGepFieldObjects_set(value);
  }

  public static String getNumOfGepFieldObjects() {
    return SUPAJNI.PTAStat_NumOfGepFieldObjects_get();
  }

  public static void setAveragePointsToSetSize(String value) {
    SUPAJNI.PTAStat_AveragePointsToSetSize_set(value);
  }

  public static String getAveragePointsToSetSize() {
    return SUPAJNI.PTAStat_AveragePointsToSetSize_get();
  }

  public static void setAverageTopLevPointsToSetSize(String value) {
    SUPAJNI.PTAStat_AverageTopLevPointsToSetSize_set(value);
  }

  public static String getAverageTopLevPointsToSetSize() {
    return SUPAJNI.PTAStat_AverageTopLevPointsToSetSize_get();
  }

  public static void setMaxPointsToSetSize(String value) {
    SUPAJNI.PTAStat_MaxPointsToSetSize_set(value);
  }

  public static String getMaxPointsToSetSize() {
    return SUPAJNI.PTAStat_MaxPointsToSetSize_get();
  }

  public static void setNumOfIterations(String value) {
    SUPAJNI.PTAStat_NumOfIterations_set(value);
  }

  public static String getNumOfIterations() {
    return SUPAJNI.PTAStat_NumOfIterations_get();
  }

  public static void setNumOfIndirectCallSites(String value) {
    SUPAJNI.PTAStat_NumOfIndirectCallSites_set(value);
  }

  public static String getNumOfIndirectCallSites() {
    return SUPAJNI.PTAStat_NumOfIndirectCallSites_get();
  }

  public static void setNumOfIndirectEdgeSolved(String value) {
    SUPAJNI.PTAStat_NumOfIndirectEdgeSolved_set(value);
  }

  public static String getNumOfIndirectEdgeSolved() {
    return SUPAJNI.PTAStat_NumOfIndirectEdgeSolved_get();
  }

  public static void setNumOfSCCDetection(String value) {
    SUPAJNI.PTAStat_NumOfSCCDetection_set(value);
  }

  public static String getNumOfSCCDetection() {
    return SUPAJNI.PTAStat_NumOfSCCDetection_get();
  }

  public static void setNumOfCycles(String value) {
    SUPAJNI.PTAStat_NumOfCycles_set(value);
  }

  public static String getNumOfCycles() {
    return SUPAJNI.PTAStat_NumOfCycles_get();
  }

  public static void setNumOfPWCCycles(String value) {
    SUPAJNI.PTAStat_NumOfPWCCycles_set(value);
  }

  public static String getNumOfPWCCycles() {
    return SUPAJNI.PTAStat_NumOfPWCCycles_get();
  }

  public static void setNumOfNodesInCycles(String value) {
    SUPAJNI.PTAStat_NumOfNodesInCycles_set(value);
  }

  public static String getNumOfNodesInCycles() {
    return SUPAJNI.PTAStat_NumOfNodesInCycles_get();
  }

  public static void setMaxNumOfNodesInSCC(String value) {
    SUPAJNI.PTAStat_MaxNumOfNodesInSCC_set(value);
  }

  public static String getMaxNumOfNodesInSCC() {
    return SUPAJNI.PTAStat_MaxNumOfNodesInSCC_get();
  }

  public static void setNumOfNullPointer(String value) {
    SUPAJNI.PTAStat_NumOfNullPointer_set(value);
  }

  public static String getNumOfNullPointer() {
    return SUPAJNI.PTAStat_NumOfNullPointer_get();
  }

  public PTAStat(PointerAnalysis p) {
    this(SUPAJNI.new_PTAStat(PointerAnalysis.getCPtr(p), p), true);
  }

  public void startClk() {
    SUPAJNI.PTAStat_startClk(swigCPtr, this);
  }

  public void endClk() {
    SUPAJNI.PTAStat_endClk(swigCPtr, this);
  }

  public static double getClk() {
    return SUPAJNI.PTAStat_getClk();
  }

  public void setGeneralNumMap(NUMStatMap value) {
    SUPAJNI.PTAStat_generalNumMap_set(swigCPtr, this, NUMStatMap.getCPtr(value), value);
  }

  public NUMStatMap getGeneralNumMap() {
    long cPtr = SUPAJNI.PTAStat_generalNumMap_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NUMStatMap(cPtr, false);
  }

  public void setPTNumStatMap(NUMStatMap value) {
    SUPAJNI.PTAStat_PTNumStatMap_set(swigCPtr, this, NUMStatMap.getCPtr(value), value);
  }

  public NUMStatMap getPTNumStatMap() {
    long cPtr = SUPAJNI.PTAStat_PTNumStatMap_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NUMStatMap(cPtr, false);
  }

  public void setTimeStatMap(TIMEStatMap value) {
    SUPAJNI.PTAStat_timeStatMap_set(swigCPtr, this, TIMEStatMap.getCPtr(value), value);
  }

  public TIMEStatMap getTimeStatMap() {
    long cPtr = SUPAJNI.PTAStat_timeStatMap_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TIMEStatMap(cPtr, false);
  }

  public void setLocalVarInRecursion(SWIGTYPE_p_llvm__SparseBitVectorT_t value) {
    SUPAJNI.PTAStat_localVarInRecursion_set(swigCPtr, this, SWIGTYPE_p_llvm__SparseBitVectorT_t.getCPtr(value));
  }

  public SWIGTYPE_p_llvm__SparseBitVectorT_t getLocalVarInRecursion() {
    return new SWIGTYPE_p_llvm__SparseBitVectorT_t(SUPAJNI.PTAStat_localVarInRecursion_get(swigCPtr, this), true);
  }

  public void setStartTime(double value) {
    SUPAJNI.PTAStat_startTime_set(swigCPtr, this, value);
  }

  public double getStartTime() {
    return SUPAJNI.PTAStat_startTime_get(swigCPtr, this);
  }

  public void setEndTime(double value) {
    SUPAJNI.PTAStat_endTime_set(swigCPtr, this, value);
  }

  public double getEndTime() {
    return SUPAJNI.PTAStat_endTime_get(swigCPtr, this);
  }

  public void performStat() {
    SUPAJNI.PTAStat_performStat(swigCPtr, this);
  }

  public void printStat(String str) {
    SUPAJNI.PTAStat_printStat__SWIG_0(swigCPtr, this, str);
  }

  public void printStat() {
    SUPAJNI.PTAStat_printStat__SWIG_1(swigCPtr, this);
  }

  public void performStatPerQuery(long ptr) {
    SUPAJNI.PTAStat_performStatPerQuery(swigCPtr, this, ptr);
  }

  public void printStatPerQuery(long ptr, SWIGTYPE_p_llvm__SparseBitVectorT_t pts) {
    SUPAJNI.PTAStat_printStatPerQuery(swigCPtr, this, ptr, SWIGTYPE_p_llvm__SparseBitVectorT_t.getCPtr(pts));
  }

  public void callgraphStat() {
    SUPAJNI.PTAStat_callgraphStat(swigCPtr, this);
  }

}
