/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class StoreToPMSetMap extends java.util.AbstractMap<SWIGTYPE_p_SVFGNode, SWIGTYPE_p_DPTItemSet> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StoreToPMSetMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StoreToPMSetMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_StoreToPMSetMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof SWIGTYPE_p_SVFGNode)) {
      return false;
    }

    return containsImpl((SWIGTYPE_p_SVFGNode)key);
  }

  public SWIGTYPE_p_DPTItemSet get(java.lang.Object key) {
    if (!(key instanceof SWIGTYPE_p_SVFGNode)) {
      return null;
    }

    Iterator itr = find((SWIGTYPE_p_SVFGNode) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public SWIGTYPE_p_DPTItemSet put(SWIGTYPE_p_SVFGNode key, SWIGTYPE_p_DPTItemSet value) {
    Iterator itr = find((SWIGTYPE_p_SVFGNode) key);
    if (itr.isNot(end())) {
      SWIGTYPE_p_DPTItemSet oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public SWIGTYPE_p_DPTItemSet remove(java.lang.Object key) {
    if (!(key instanceof SWIGTYPE_p_SVFGNode)) {
      return null;
    }

    Iterator itr = find((SWIGTYPE_p_SVFGNode) key);
    if (itr.isNot(end())) {
      SWIGTYPE_p_DPTItemSet oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<SWIGTYPE_p_SVFGNode, SWIGTYPE_p_DPTItemSet>> entrySet() {
    java.util.Set<Entry<SWIGTYPE_p_SVFGNode, SWIGTYPE_p_DPTItemSet>> setToReturn =
        new java.util.HashSet<Entry<SWIGTYPE_p_SVFGNode, SWIGTYPE_p_DPTItemSet>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<SWIGTYPE_p_SVFGNode, SWIGTYPE_p_DPTItemSet>() {
        private Iterator iterator;

        private Entry<SWIGTYPE_p_SVFGNode, SWIGTYPE_p_DPTItemSet> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public SWIGTYPE_p_SVFGNode getKey() {
          return iterator.getKey();
        }

        public SWIGTYPE_p_DPTItemSet getValue() {
          return iterator.getValue();
        }

        public SWIGTYPE_p_DPTItemSet setValue(SWIGTYPE_p_DPTItemSet newValue) {
          SWIGTYPE_p_DPTItemSet oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public StoreToPMSetMap() {
    this(SUPAJNI.new_StoreToPMSetMap__SWIG_0(), true);
  }

  public StoreToPMSetMap(StoreToPMSetMap other) {
    this(SUPAJNI.new_StoreToPMSetMap__SWIG_1(StoreToPMSetMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SUPAJNI.delete_StoreToPMSetMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private StoreToPMSetMap.Iterator getNextUnchecked() {
      return new StoreToPMSetMap.Iterator(SUPAJNI.StoreToPMSetMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(StoreToPMSetMap.Iterator other) {
      return SUPAJNI.StoreToPMSetMap_Iterator_isNot(swigCPtr, this, StoreToPMSetMap.Iterator.getCPtr(other), other);
    }
  
    private SWIGTYPE_p_SVFGNode getKey() {
      long cPtr = SUPAJNI.StoreToPMSetMap_Iterator_getKey(swigCPtr, this);
      return (cPtr == 0) ? null : new SWIGTYPE_p_SVFGNode(cPtr, false);
    }
  
    private SWIGTYPE_p_DPTItemSet getValue() {
      return new SWIGTYPE_p_DPTItemSet(SUPAJNI.StoreToPMSetMap_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(SWIGTYPE_p_DPTItemSet newValue) {
      SUPAJNI.StoreToPMSetMap_Iterator_setValue(swigCPtr, this, SWIGTYPE_p_DPTItemSet.getCPtr(newValue));
    }
  
  }

  public boolean isEmpty() {
    return SUPAJNI.StoreToPMSetMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SUPAJNI.StoreToPMSetMap_clear(swigCPtr, this);
  }

  private StoreToPMSetMap.Iterator find(SWIGTYPE_p_SVFGNode key) {
    return new StoreToPMSetMap.Iterator(SUPAJNI.StoreToPMSetMap_find(swigCPtr, this, SWIGTYPE_p_SVFGNode.getCPtr(key)), true);
  }

  private StoreToPMSetMap.Iterator begin() {
    return new StoreToPMSetMap.Iterator(SUPAJNI.StoreToPMSetMap_begin(swigCPtr, this), true);
  }

  private StoreToPMSetMap.Iterator end() {
    return new StoreToPMSetMap.Iterator(SUPAJNI.StoreToPMSetMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return SUPAJNI.StoreToPMSetMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(SWIGTYPE_p_SVFGNode key) {
    return SUPAJNI.StoreToPMSetMap_containsImpl(swigCPtr, this, SWIGTYPE_p_SVFGNode.getCPtr(key));
  }

  private void putUnchecked(SWIGTYPE_p_SVFGNode key, SWIGTYPE_p_DPTItemSet value) {
    SUPAJNI.StoreToPMSetMap_putUnchecked(swigCPtr, this, SWIGTYPE_p_SVFGNode.getCPtr(key), SWIGTYPE_p_DPTItemSet.getCPtr(value));
  }

  private void removeUnchecked(StoreToPMSetMap.Iterator itr) {
    SUPAJNI.StoreToPMSetMap_removeUnchecked(swigCPtr, this, StoreToPMSetMap.Iterator.getCPtr(itr), itr);
  }

}
