/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public interface SUPAConstants {
  public final static double M_E = SUPAJNI.M_E_get();
  public final static double M_LOG2E = SUPAJNI.M_LOG2E_get();
  public final static double M_LOG10E = SUPAJNI.M_LOG10E_get();
  public final static double M_LN2 = SUPAJNI.M_LN2_get();
  public final static double M_LN10 = SUPAJNI.M_LN10_get();
  public final static double M_PI = SUPAJNI.M_PI_get();
  public final static double M_PI_2 = SUPAJNI.M_PI_2_get();
  public final static double M_PI_4 = SUPAJNI.M_PI_4_get();
  public final static double M_1_PI = SUPAJNI.M_1_PI_get();
  public final static double M_2_PI = SUPAJNI.M_2_PI_get();
  public final static double M_2_SQRTPI = SUPAJNI.M_2_SQRTPI_get();
  public final static double M_SQRT2 = SUPAJNI.M_SQRT2_get();
  public final static double M_SQRT1_2 = SUPAJNI.M_SQRT1_2_get();
  public final static String DGENERAL = SUPAJNI.DGENERAL_get();
  public final static String DPAGBuild = SUPAJNI.DPAGBuild_get();
  public final static String DMemModel = SUPAJNI.DMemModel_get();
  public final static String DMemModelCE = SUPAJNI.DMemModelCE_get();
  public final static String DCOMModel = SUPAJNI.DCOMModel_get();
  public final static String DDDA = SUPAJNI.DDDA_get();
  public final static String DDumpPT = SUPAJNI.DDumpPT_get();
  public final static String DRefinePT = SUPAJNI.DRefinePT_get();
  public final static String DCache = SUPAJNI.DCache_get();
  public final static String DWPA = SUPAJNI.DWPA_get();
  public final static String DMSSA = SUPAJNI.DMSSA_get();
  public final static String DInstrument = SUPAJNI.DInstrument_get();
  public final static String DAndersen = SUPAJNI.DAndersen_get();
  public final static String DSaber = SUPAJNI.DSaber_get();
  public final static String DMTA = SUPAJNI.DMTA_get();
  public final static String DCHA = SUPAJNI.DCHA_get();
  public final static int TIMEINTERVAL = SUPAJNI.TIMEINTERVAL_get();
}
