/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.supa.bindings;

public class SVFModule {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SVFModule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SVFModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SUPAJNI.delete_SVFModule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SVFModule(StringVector moduleNameVec) {
    this(SUPAJNI.new_SVFModuleMNV(StringVector.getCPtr(moduleNameVec), moduleNameVec), true);
  }

  public SVFModule(SWIGTYPE_p_llvm__Module mod) {
    this(SUPAJNI.new_SVFModulePointer(SWIGTYPE_p_llvm__Module.getCPtr(mod)), true);
  }

  public SVFModule(SWIGTYPE_p_llvm__Module mod) {
    this(SUPAJNI.new_SVFModuleAddr(SWIGTYPE_p_llvm__Module.getCPtr(mod)), true);
  }

  public SVFModule() {
    this(SUPAJNI.new_SVFModule(), true);
  }

  public static LLVMModuleSet getLLVMModuleSet() {
    long cPtr = SUPAJNI.SVFModule_getLLVMModuleSet();
    return (cPtr == 0) ? null : new LLVMModuleSet(cPtr, false);
  }

  public static void setPagFromTXT(String txt) {
    SUPAJNI.SVFModule_setPagFromTXT(txt);
  }

  public static String pagFileName() {
    return SUPAJNI.SVFModule_pagFileName();
  }

  public static boolean pagReadFromTXT() {
    return SUPAJNI.SVFModule_pagReadFromTXT();
  }

  public static void releaseLLVMModuleSet() {
    SUPAJNI.SVFModule_releaseLLVMModuleSet();
  }

  public boolean empty() {
    return SUPAJNI.SVFModule_empty(swigCPtr, this);
  }

  public long getModuleNum() {
    return SUPAJNI.SVFModule_getModuleNum(swigCPtr, this);
  }

  public SWIGTYPE_p_llvm__Module getModule(long idx) {
    long cPtr = SUPAJNI.SVFModule_getModule(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__Module(cPtr, false);
  }

  public SWIGTYPE_p_llvm__Module getModuleRef(long idx) {
    return new SWIGTYPE_p_llvm__Module(SUPAJNI.SVFModule_getModuleRef(swigCPtr, this, idx), false);
  }

  public void dumpModulesToFile(String suffix) {
    SUPAJNI.SVFModule_dumpModulesToFile(swigCPtr, this, suffix);
  }

  public boolean hasDefinition(SWIGTYPE_p_llvm__Function fun) {
    return SUPAJNI.SVFModule_hasDefinition(swigCPtr, this, SWIGTYPE_p_llvm__Function.getCPtr(fun));
  }

  public SWIGTYPE_p_llvm__Function getDefinition(SWIGTYPE_p_llvm__Function fun) {
    long cPtr = SUPAJNI.SVFModule_getDefinition(swigCPtr, this, SWIGTYPE_p_llvm__Function.getCPtr(fun));
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__Function(cPtr, false);
  }

  public boolean hasDeclaration(SWIGTYPE_p_llvm__Function fun) {
    return SUPAJNI.SVFModule_hasDeclaration(swigCPtr, this, SWIGTYPE_p_llvm__Function.getCPtr(fun));
  }

  public FunctionSetType getDeclaration(SWIGTYPE_p_llvm__Function fun) {
    return new FunctionSetType(SUPAJNI.SVFModule_getDeclaration(swigCPtr, this, SWIGTYPE_p_llvm__Function.getCPtr(fun)), false);
  }

  public boolean hasGlobalRep(SWIGTYPE_p_llvm__GlobalVariable val) {
    return SUPAJNI.SVFModule_hasGlobalRep(swigCPtr, this, SWIGTYPE_p_llvm__GlobalVariable.getCPtr(val));
  }

  public SWIGTYPE_p_llvm__GlobalVariable getGlobalRep(SWIGTYPE_p_llvm__GlobalVariable val) {
    long cPtr = SUPAJNI.SVFModule_getGlobalRep(swigCPtr, this, SWIGTYPE_p_llvm__GlobalVariable.getCPtr(val));
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__GlobalVariable(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_llvm__Function_p_t__iterator begin() {
    return new SWIGTYPE_p_std__vectorT_llvm__Function_p_t__iterator(SUPAJNI.SVFModule_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_llvm__Function_p_t__const_iterator begin_const() {
    return new SWIGTYPE_p_std__vectorT_llvm__Function_p_t__const_iterator(SUPAJNI.SVFModule_begin_const(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_llvm__Function_p_t__iterator end() {
    return new SWIGTYPE_p_std__vectorT_llvm__Function_p_t__iterator(SUPAJNI.SVFModule_end(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_llvm__Function_p_t__const_iterator end_const() {
    return new SWIGTYPE_p_std__vectorT_llvm__Function_p_t__const_iterator(SUPAJNI.SVFModule_end_const(swigCPtr, this), true);
  }

  public SWIGTYPE_p_llvm__Module getMainLLVMModule() {
    long cPtr = SUPAJNI.SVFModule_getMainLLVMModule(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__Module(cPtr, false);
  }

  public String getModuleIdentifier() {
    return SUPAJNI.SVFModule_getModuleIdentifier(swigCPtr, this);
  }

  public SWIGTYPE_p_llvm__LLVMContext getContext() {
    return new SWIGTYPE_p_llvm__LLVMContext(SUPAJNI.SVFModule_getContext(swigCPtr, this), false);
  }

  public SWIGTYPE_p_llvm__Function getFunction(SWIGTYPE_p_llvm__StringRef name) {
    long cPtr = SUPAJNI.SVFModule_getFunction(swigCPtr, this, SWIGTYPE_p_llvm__StringRef.getCPtr(name));
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__Function(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_llvm__GlobalVariable_p_t__iterator global_begin() {
    return new SWIGTYPE_p_std__vectorT_llvm__GlobalVariable_p_t__iterator(SUPAJNI.SVFModule_global_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_llvm__GlobalVariable_p_t__const_iterator global_begin_const() {
    return new SWIGTYPE_p_std__vectorT_llvm__GlobalVariable_p_t__const_iterator(SUPAJNI.SVFModule_global_begin_const(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_llvm__GlobalVariable_p_t__iterator global_end() {
    return new SWIGTYPE_p_std__vectorT_llvm__GlobalVariable_p_t__iterator(SUPAJNI.SVFModule_global_end(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_llvm__GlobalVariable_p_t__const_iterator global_end_const() {
    return new SWIGTYPE_p_std__vectorT_llvm__GlobalVariable_p_t__const_iterator(SUPAJNI.SVFModule_global_end_const(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_llvm__GlobalAlias_p_t__iterator alias_begin() {
    return new SWIGTYPE_p_std__vectorT_llvm__GlobalAlias_p_t__iterator(SUPAJNI.SVFModule_alias_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_llvm__GlobalAlias_p_t__const_iterator alias_begin_const() {
    return new SWIGTYPE_p_std__vectorT_llvm__GlobalAlias_p_t__const_iterator(SUPAJNI.SVFModule_alias_begin_const(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_llvm__GlobalAlias_p_t__iterator alias_end() {
    return new SWIGTYPE_p_std__vectorT_llvm__GlobalAlias_p_t__iterator(SUPAJNI.SVFModule_alias_end(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_llvm__GlobalAlias_p_t__const_iterator alias_end_const() {
    return new SWIGTYPE_p_std__vectorT_llvm__GlobalAlias_p_t__const_iterator(SUPAJNI.SVFModule_alias_end_const(swigCPtr, this), true);
  }

}
